#DB
SPRING_DATASOURCE_URL= jdbc:mysql://localhost:3306/NearSee
SPRING_DATASOURCE_PASSWORD= *Root

#KAKAO
KAKAO_LOGIN_ID = ffe5382147a1178ca09ce3dc5fadfee8
KAKAO_LOGIN_SECRECT_KEY = mZwlvr8JIYurWBNTezEJ7iX8m7YyAvut
